// Generated by https://quicktype.io

export interface UserSearchResponse {
    status: number;
    message: string;
    data: UserDataResponse;
    token: string;
}

export interface UserDataResponse {
    total_rows: number;
    per_page: number;
    page: number;
    total_pages: number;
    data: UserEntity[];
}

export interface UserEntity {
    id: string;
    full_name: string;
    is_user_role_cat_id: string;
    is_user_role_cat_name: string;
    is_account_main_id: string;
    is_account_main_name: string;
    original_account_id: string;
    original_account_name: string;
    user_raw_salary: null | string;
    profile_picture: string;
}
